from selenium.webdriver.common.by import By

exercise_page_title = (By.CLASS_NAME, 'col-lg-12')
exercise_catalog = (By.CLASS_NAME, 'panel-title')
press_ex1 = (By.PARTIAL_LINK_TEXT, 'Подъемы коленей в висе')
press_description = (By.CSS_SELECTOR, 'div[id="exerciseDetails"]')
description_statistics_btn = (By.XPATH, '//a[@href="#tabStats" and @data-toggle="tab"]')
info_statistics = (By.CSS_SELECTOR, 'div[id="tabStats"]')
description_history_btn = (By.XPATH, '//a[@href="#tabHistory" and @data-toggle="tab"]')
info_history = (By.CLASS_NAME, 'emptyWorkout')
oneself_exercises = (By.PARTIAL_LINK_TEXT, 'Мои')
new_exercise_field = (By.CSS_SELECTOR, 'input[placeholder="Новое упражнение"]')
add_new_exercise_button = (By.CSS_SELECTOR, 'button[class="btn btn-orange btn-block"]')
pop_up_message = (By.CSS_SELECTOR, 'div[class="sticky-queue top-right"]')
type_of_exercise_field = (By.CSS_SELECTOR, 'select[class="form-control"]')
save_exercise_details = (By.CSS_SELECTOR, 'button[class="btn btn-orange pull-right"]')
delete_exercise = (By.ID, 'removeExercise')
yes_delete_exercise = (By.CSS_SELECTOR, 'button[class="btn btn-default"]')
no_delete_exercise = (By.CSS_SELECTOR, 'button[class="btn btn-primary"]')
saved_personal_exercise = (By.XPATH, '//input[@value="Hiit" and @class="form-control"]')
search_button = (By.PARTIAL_LINK_TEXT, 'Поиск')
search_exercise_field = (By.CSS_SELECTOR, 'input[placeholder="Искать упражнение"]')
positive_search_result = (By.ID, 'searchResult')
negative_search_result = (By.CSS_SELECTOR, 'td[class="exerciseDetailsTd"]')
