from selenium.webdriver.common.by import By

reg_btn_at_the_top_of_the_page = (By.XPATH, '//a[@id="btn-reg" and @class="btn"]')
redirecting_reg_btn = (By.XPATH, '//a[@class="cta priceBg4" and @data-action="pulse"]')
welcome_block = (By.CSS_SELECTOR, 'span[class="hidden-xs"]')
login_button = (By.XPATH, '//a[@class="btn" and @style="font-size: 12px"]')
show_only_active_days_box = (By.CSS_SELECTOR, 'label[for="showOnlyActive"]')
all_days_of_the_month_block = (By.CSS_SELECTOR, 'div[class="main-box-body clearfix"]')
rec_workout_in_december = (By.CSS_SELECTOR, 'button[onclick="page_workout.create(11)"]')
plus_workout_in_december = (By.CSS_SELECTOR, 'a[class="exerciseName new hint--right hint--always"]')
exercise_selection_window = (By.ID, 'modalExercisesContent')
list_of_exercises_in_the_selection_window = (By.CLASS_NAME, 'panel-heading')
biceps_ex = (By.LINK_TEXT, 'Сгибание рук со штангой')
displayed_exercise = (By.XPATH, '//span[text()="Сгибание рук со штангой"]')
comment_to_the_exercise = (By.CSS_SELECTOR, 'a[class="comment empty"]')
comment_field = (By.CSS_SELECTOR, 'input[placeholder="Комментарий"]')
comment_done = (By.CSS_SELECTOR, 'button[class="btn btn-orange btn-item-comment-save"]')
remove_an_exercise = (By.CSS_SELECTOR, 'button[class="btn btn-default btn-item-delete mb20"]')
all_menu = (By.CLASS_NAME, 'navLabel ')
profile_block = (By.CLASS_NAME, 'profile-dropdown')
profile_menu_settings = (By.CSS_SELECTOR, 'a[href="/settings"]')
profile_menu_exit = (By.CSS_SELECTOR, 'a[href="/logout"]')